<?php

namespace Database\Seeders;
use App\Models\Country;
use Illuminate\Database\Seeder;


class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $info = Country::latest()->first();
        if (is_null($info)) {
            $countryList = array(
                 'BANGLADESH',
                 'AFGHANISTAN',
                 'ALBANIA',
                 'ALGERIA',
                 'ANDORRA',
                 'ANGOLA',
                 'ANGUILLA',
                 'ANTARCTICA',
                 'ARGENTINA',
                 'ARMENIA',
                 'ARUBA',
                 'AUSTRALIA',
                 'AUSTRIA',
                 'AZERBAIJAN',
                 'BAHAMAS',
                 'BAHRAIN',
                 'BARBADOS',
                 'BELARUS',
                 'BELGIUM',
                 'BELIZE',
                 'BENIN',
                 'BERMUDA',
                 'BHUTAN',
                 'BOLIVIA',
                 'BOTSWANA',
                 'BOUVET ISLAND',
                 'BRAZIL',
                 'BULGARIA',
                 'BURKINA FASO',
                 'BURUNDI',
                 'CAMBODIA',
                 'CAMEROON',
                 'CANADA',
                 'CHAD',
                 'CHILE',
                 'CHINA',
                 'COLOMBIA',
                 'COMOROS',
                 'CONGO',
                 'CROATIA',
                 'CUBA',
                 'CYPRUS',
                 'DENMARK',
                 'DJIBOUTI',
                 'DOMINICA',
                 'EGYPT',
                 'FIJI',
                 'FINLAND',
                 'FRANCE',
                 'GABON',
                 'GAMBIA',
                 'GEORGIA',
                 'GERMANY',
                 'GHANA',
                 'GIBRALTAR',
                 'GREECE',
                 'GREENLAND',
                 'GRENADA',
                 'GUADELOUPE',
                 'GUAM',
                 'GUATEMALA',
                 'GUINEA',
                 'GUINEA-BISSAU',
                 'GUYANA',
                 'HAITI',
                 'HONG KONG',
                 'HUNGARY',
                 'ICELAND',
                 'INDIA',
                 'INDONESIA',
                 'IRAN',
                 'IRAQ',
                 'IRELAND',
                 'ISRAEL',
                 'ITALY',
                 'JAMAICA',
                 'JAPAN',
                 'JORDAN',
                 'KAZAKSTAN',
                 'KENYA',
                 'KIRIBATI',
                 'KOREA',
                 'KUWAIT',
                 'KYRGYZSTAN',
                 'LATVIA',
                 'LEBANON',
                 'LESOTHO',
                 'LIBERIA',
                 'MALAYSIA',
                 'MALDIVES',
                 'MALI',
                 'MALTA',
                 'MEXICO',
                 'MONACO',
                 'MONGOLIA',
                 'MONTSERRAT',
                 'MOROCCO',
                 'MOZAMBIQUE',
                 'MYANMAR',
                 'NAMIBIA',
                 'NAURU',
                 'NEPAL',
                 'NETHERLANDS',
                 'NICARAGUA',
                 'NIGER',
                 'NIGERIA',
                 'NIUE',
                 'NORWAY',
                 'OMAN',
                 'PAKISTAN',
                 'PALAU',
                 'QATAR',
                 'REUNION',
                 'ROMANIA',
                 'RUSSIAN',
                 'SAUDI ARABIA',
                 'SENEGAL',
                 'SEYCHELLES',
                 'SIERRA LEONE',
                 'SINGAPORE',
                 'SLOVAKIA',
                 'SLOVENIA',
                 'SOMALIA',
                 'SRI LANKA',
                 'SWAZILAND',
                 'SWEDEN',
                 'SWITZERLAND',
                 'TAJIKISTAN',
                 'THAILAND',
                 'TOGO',
                 'TOKELAU',
                 'TONGA',
                 'TUNISIA',
                 'TURKEY',
                 'TURKMENISTAN',
                 'TURKS',
                 'TUVALU',
                 'UGANDA',
                 'UKRAINE',
                 'ARAB EMIRATES',
                 'UNITED KINGDOM',
                 'UNITED STATES',
                
            );
    
            foreach ($countryList as $county) {
                $count = new Country();
                $count->country_name = $county;
                $count->superadmin_id = 1;
                $count->save();
            }
    
            
        }
    }
}
